// Generated by CoffeeScript 2.4.1
var ETH;

ETH = class ETH {
  constructor() {
    this.ws = null;
    // wss://ws.blockchain.info/coins - unconfirmed TX
    // wss://etherscan.io/wshandler - blocks
    this.socketUrl = "wss://ethersocket.herokuapp.com";
    this.donationAddress = "0xf3Ac6fFCD6451682a753695e56425038dE2b79DD";
  }

  start(txCb, blockCb) {
    if (this.ws) {
      this.stop();
    }
    this.ws = new WebSocket(this.socketUrl);
    this.ws.onclose = () => {
      return setTimeout((() => {
        return this.start(txCb, blockCb);
      }), 1000);
    };
    this.ws.onopen = () => {};
    //@ws.send '2probe'
    //@ws.send '5'
    //@ping = setInterval (=> @ws.send '2'), 25*1000
    return this.ws.onmessage = ({data}) => {
      data = JSON.parse(data);
      if (data.from != null) {
        return typeof txCb === "function" ? txCb({
          amount: data.value / 1000000000000000000,
          fee: data.gas * data.gasPrice / 1000000000000000000,
          link: 'https://etherscan.io/tx/0x' + data.hash.substr(2),
          donation: data.to === this.donationAddress
        }) : void 0;
      } else {
        return typeof blockCb === "function" ? blockCb({
          count: data.numTransactions
        }) : void 0;
      }
    };
  }

  stop() {
    this.ws.close();
    //clearInterval @ping
    return this.ws = null;
  }

};

//# sourceMappingURL=eth.js.map
