// Generated by CoffeeScript 2.2.0
var ETH;

ETH = class ETH {
  constructor() {
    this.ws = null;
    this.socketUrl = "wss://ethersocket.herokuapp.com";
    this.donationAddress = "0xf3Ac6fFCD6451682a753695e56425038dE2b79DD";
  }

  start(txCb, blockCb) {
    if (this.ws) {
      this.stop();
    }
    this.ws = new WebSocket(this.socketUrl);
    this.ws.onclose = () => {
      return setTimeout((() => {
        return this.start(txCb, blockCb);
      }), 1000);
    };
    return this.ws.onmessage = ({data}) => {
      data = JSON.parse(data);
      if (data.type === 'tx') {
        return typeof txCb === "function" ? txCb({
          amount: data.ethers,
          fee: data.fee,
          link: 'https://etherscan.io/tx/' + data.hash,
          donation: data.to === this.donationAddress
        }) : void 0;
      } else {
        return typeof blockCb === "function" ? blockCb({
          count: data.transactions
        }) : void 0;
      }
    };
  }

  stop() {
    this.ws.close();
    return this.ws = null;
  }

};

//# sourceMappingURL=eth.js.map
