// Generated by CoffeeScript 2.4.1
var NANO;

NANO = class NANO {
  constructor() {
    this.ws = null;
    this.socketUrl = "wss://ws.nanocrawler.cc/";
    this.donationAddress = "nano_1em33f7ewc9mpbargkp14m3uuojz5wt96hzu4tcfb585ds8575gp1fnoxaj3";
  }

  start(txCb) {
    if (this.ws) {
      this.stop();
    }
    this.ws = new WebSocket(this.socketUrl);
    this.ws.onclose = () => {
      return setTimeout((() => {
        return this.start(txCb, blockCb);
      }), 1000);
    };
    this.ws.onopen = () => {
      this.ws.send(JSON.stringify({
        event: 'subscribe',
        data: ['all']
      }));
      return this.ping = setInterval((() => {
        return this.ws.send(JSON.stringify({
          event: 'keepalive'
        }));
      }), 30 * 1000);
    };
    return this.ws.onmessage = ({data}) => {
      var amount, link_as_account;
      data = JSON.parse(data);
      if (data.data && data.data.is_send === 'true') {
        ({amount, link_as_account} = data.data.block);
        return typeof txCb === "function" ? txCb({
          amount: amount,
          fee: 0,
          link: 'https://nanocrawler.cc/explorer/block/' + data.data.hash,
          donation: link_as_account === this.donationAddress
        }) : void 0;
      }
    };
  }

  stop() {
    this.ws.close();
    clearInterval(this.ping);
    return this.ws = null;
  }

};

//# sourceMappingURL=nano.js.map
