// Generated by CoffeeScript 2.2.0
var XRB;

XRB = class XRB {
  constructor() {
    this.ws = null;
    this.socketUrl = "wss://www.nanode.co/socket.io/?EIO=3&transport=websocket";
    this.donationAddress = "xrb_1ac4dntxugbfxsmmy6wimddwiju7em7qi6zp8ri6fx566swq4j56gwd9ibxw";
  }

  start(txCb) {
    if (this.ws) {
      this.stop();
    }
    this.ws = new WebSocket(this.socketUrl);
    this.ws.onopen = () => {
      return this.ping = setInterval((() => {
        return this.ws.send('2');
      }), 25 * 1000);
    };
    return this.ws.onmessage = ({data}) => {
      var payload, type;
      data = data.match(/^\d+(\[.+?)$/);
      if (data) {
        [type, payload] = JSON.parse(data[1]);
        if (type === 'block' && (payload.type === 'send' || payload.type === 'receive')) {
          return typeof txCb === "function" ? txCb({
            amount: payload.amount / Math.pow(10, 30),
            fee: 0,
            link: 'https://www.nanode.co/block/' + payload.hash,
            donation: payload.account === this.donationAddress
          }) : void 0;
        }
      }
    };
  }

  stop() {
    this.ws.close();
    clearInterval(this.ping);
    return this.ws = null;
  }

};

//# sourceMappingURL=xrb.js.map
